# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shoya Iwanami / 岩波翔也
email: iwanamishoya[at]gmail.com
organizer: 岩波翔也
affiliation: 九州大学数理生物学研究室
address: 〒819-0395 福岡市西区元岡744 九州大学伊都キャンパス ウエスト１号館C-911
description: >- # this means to ignore newlines until "baseurl:"
  こんにちは。岩波翔也です。九州大学大学院理学研究院生物科学部門/数理生物学研究室に所属しています。Shoya Iwanami, Mathematical Biology Labolatory, Graduate School of Systems Life Sciences, Kyushu University, Japan
keywords: 岩波翔也,岩波,翔也,九州大学,数理生物,免疫,理論免疫,Shoya Iwanami,Shoya,Iwanami,Kyushu University,Mathematical Biology,Immunology,Theoretical Immunology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shoyaiwanami.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
permalink: pretty
google_analytics: UA-85165915-4
# google_maps: AIzaSyCmNAoJl7rD3i-J8BotDmoHjNO1O-ipa1w

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
