# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 岩波翔也 / Shoya Iwanami
organizer: 岩波翔也 / Shoya Iwanami
affiliation: 名古屋大学大学院理学研究科生命理学専攻
possition: 助教
laboratory:
  name_jp: 異分野融合生物学研究室（iBLab）
  name_en: interdisciplinary Biology Laboratory
  url: https://iblab.bio.nagoya-u.ac.jp/
email: iwanamishoya[at]gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  こんにちは。岩波翔也です。名古屋大学大学院理学研究科生命理学専攻/異分野融合生物学研究室に所属しています。Shoya Iwanami, interdisciplinary Biology Laboratory, Division of Biological Science, Graduate School of Science, Nagoya University, Japan
keywords: 岩波翔也,岩波,翔也,異分野融合,名古屋大学,九州大学,数理生物,免疫,理論免疫,Shoya Iwanami,Shoya,Iwanami,Nagoya University,Kyushu University,Mathematical Biology,Immunology,Theoretical Immunology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shoyaiwanami.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
google_analytics: UA-85165915-4

# Build settings

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
